### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by Notaduck** [dalesnail/themite#2]
There seems to be an issue with the program, I'm not able to change theme?

```

       ▄▄▄▄▄▄     ▄ .▄    ▄▄▄ .    • ▄   ▄▄ ·.   ▀    ▄▄▄▄▄▄    ▄▄▄ .
        •██ ·    ██ ▐█    █ .▀·    ·██▄▐███ ▪   ██     •██      ▀▄.▀·
      ·  ▐█.▪·   ██▄ █  · █▀▀      ▐█ █▐▌▐█·    ▐█·   █ ▐█      █▀▀ ▄
       · ▐█▌·    █  ▐█    █ ▄▄▌ ·  ██ ██▌▐█▌ ·  ▐█▌     ▐█▌·    ▐█▄▄▌  ·
         ▀▀▀     ▀   █    █▀▀▀     ▀▀  █ ▀▀▀    ▀▀▀  ·  ▀▀▀  ·  ·  ·  

             1.              2.                3.                4. 
        _______________________________________________________________ 
       |                                                               |
      |   RANDOM   |   LIST THEMES   |   CHOOSE THEME   |  CHANGE FONT  |
       |_______________________________________________________________|

3
vampire
onedark
default
papercolorfork
sorcerer
Theme: vampire
Traceback (most recent call last):
  File "/home/daniel/.config/themite/termite.py", line 76, in <module>
    theme_swap(theme_dir + input("Theme: "))
  File "/home/daniel/.config/themite/termite.py", line 40, in theme_swap
    end = content.index('\n[end-colors')
ValueError: substring not found
```

**Comment by dalesnail** [comment]
I would get this error when forgetting to end my color blocks in either my main config, or a theme file with [end-colors]

For example, if this is how my config color block ends:

```
#white
color7  = #
color15 = #
[end-colors]

```


It looks here to be referring to your main config, check that out and let me know!

**Comment by Notaduck** [comment]
Thanks! that seems to have been the issue!
